### ISSUE TITLE
Windows Docker Deploy

### ISSUE THREAD

**Issue by njabulomp** [Azure/azure-iot-pcs-remote-monitoring-dotnet#125]
Good day,

This might be a simple problem, but I would like to know how to deploy the microservices in windows server 2016 with containers on Azure VM in Docker. I managed to build, publish, pull and start the microservices in Docker in the preconfigured linux VM by following the developer reference. I've been stuck on this for a while and would gladly welcome some assistance.

**Comment by asdonald** [comment]
@njabulomp Thanks for your question! Just to clarify, you were able to get this working on Linux but not windows?

**Comment by njabulomp** [comment]
@ asdonald, Hi thank you for the response, yes I was able to update the microservices, push and pull the modifications from my docker hub and start the containers in the linux vm, I tried the same on Windows without much success. I am new to docker and containers so this is a learning process for me as well.

**Comment by asdonald** [comment]
@njabulomp  

Docker is cross platform so you should really be able to run the containers in Windows. 

One detail not clear from the GitHub question, is whether the you want to run the containers in a single Windows machine or multiple machines, i.e. basic vs standard deployment. The basic deployment is very simple to run, using Docker Compose and a single configuration file similar to this: https://github.com/Azure/remote-monitoring-services-dotnet/blob/master/scripts/local/docker-compose.yml

The standard version should run on Windows too, it’s just a more complex configuration because you will need to setup Kubernetes on yourWindows machines. There should be a tutorial on this online. 

Running the containers in Windows is very much possible, and that for the Docker microservices to work together, you either manually create a Docker Network, or you should use Docker Compose which takes care of wiring the services together. Check out the Docker Compose configuration file linked above, as an example of the configuration they need to create to start all the services.

Hopefully that helps!
