### ISSUE TITLE
Azure Device Explorer Twin Error

### ISSUE THREAD

**Issue by jcbendernh** [Azure/azure-iot-pcs-remote-monitoring-dotnet#43]
# Type of issue

- [ x] Bug
- [ ] New feature
- [ ] Improvement

# Description

Cannot connect to the device via the Azure Device Explorer Twin

# Steps to reproduce

1.  I have created the new Remote Monitoring using the Basic / .Net option.
2.  Using the Azure Device Explorer Twin, I have copied my Azure IoT Hub credentials into the IoT Hub Connection String, for example...

HostName=cfs365rmd5356.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=yBc7eRGMhLbOAXCvtE6/rI1bFKXOAhrGYcwisNu16ms=

3. I click update and then I go to the Data tab and select a Device ID that is streaming date and click Monitor.

# Expected behavior
I would see the streaming JSON data in the Event Hub Data window.
...

# Current behavior
I receive the following error...

Receiving events...
Stopped Monitoring events. At least one receiver for the endpoint is created with epoch of '1', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected. TrackingId:eb61f3d3-2c4a-4ab4-9362-694f803a6157_B5, SystemTracker:iothub-ns-cfs365v3b8-254072-f2e846dcb1:eventhub:cfs365v3b8627~32766, Timestamp:11/4/2017 12:10:08 PM Reference:b4ce1ddf-7641-4e7c-b7e5-56d0b8b9b8af, TrackingId:a19ee7f7-0d33-4682-8217-6cf94aeca39c_B5, SystemTracker:iothub-ns-cfs365v3b8-254072-f2e846dcb1:eventhub:cfs365v3b8627~32766|$default, Timestamp:11/4/2017 12:10:08 PM TrackingId:eb5d3594c4284da0bca9ffed025e4c0e_G9, SystemTracker:gateway6, Timestamp:11/4/2017 12:10:08 PM
![device twin error](https://user-images.githubusercontent.com/16260984/32409813-7a88334a-c189-11e7-97a4-724c2659ed09.png)

# Known workarounds
None
...

# Possible solution
I am not sure as this works on my other IoT Hubs, including ones created by the legacy Remote Monitoring solution.
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by timlaverty** [comment]
I suspect you have more than one reader on the stream already.  Please read the following:

   ```https://blogs.msdn.microsoft.com/gyan/2014/09/02/event-hubs-receiver-epoch/
https://community.hortonworks.com/questions/80711/getting-connectionerrorexception-while-reading-dev.html
https://github.com/Azure/amqpnetlite/issues/162```

If you stop these receivers deviceexplorer should be able to read from your eventhub sitting behind the IoTHub.

Also, in the future please file DeviceExplorer bugs here:
   ```https://github.com/Azure/azure-iot-sdk-csharp/issues```
This tool is a CSharp SDK tool:
   ```https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer```

**Comment by faister** [comment]
I got the same issue. While @timlaverty is right to say that this is due to having more than one reader on the stream, it is still an issue nevertheless and I reckon that this should be called out as an Improvement. At the very least would be helpful to explain in this repo's documentation about how to circumvent this issue. The Telemetry Agent is already reading off the IoT Hub EH compatible endpoint with the consumer group $Default. Hence what I did was I use Azure CLI to create another consumer group. These are the steps:
1. az login
2. az iot hub consumer-group create --hub-name "{IoTHubname}" --name {consumer group name}
3. az iot hub consumer-group list --hub-name "{IoTHubname}"

You will see $Default and your new consumer group name. Then in your Device Explorer (Windows version), in the Data tab, click the Enable checkbox next to Consumer Group and enter your consumer group. You should be able to see the events streaming off IoT Hub for any of the simulated devices.

**Comment by timlaverty** [comment]
@faister thanks for adding the instructions.  What we plan to do in the future is create a separate group, leaving the default alone.  This should eliminate the bulk of cases (though still could happen if folks put multiple readers on the other stream).  @ppathan @hegate for FYI.
